# Generated by Django 4.0.5 on 2022-07-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('phone', models.TextField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address_line_1', models.TextField()),
                ('address_line_2', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zipcode', models.TextField()),
            ],
        ),
    ]
